<?php
  if( $metainfo_title = $this->toolkit->getMetaInfo()->getMetaTitle() )
    $this->meta_title = $metainfo_title;
  if( $metainfo_keywords = $this->toolkit->getMetaInfo()->getMetaKeywords() )
    $this->meta_keywords = $metainfo_keywords;
  if( $metainfo_description = $this->toolkit->getMetaInfo()->getMetaDescription() )
    $this->meta_description = $metainfo_description;
?>
{{default for='$#meta_title'}}
  {{optional for='$#title'}}<title>{$#title} | {$#toolkit.common_settings.site_title|raw}</title>{{/optional}}
  {{default for='$#title'}}<title>{$#toolkit.common_settings.site_title|raw}</title>{{/default}}
{{/default}}
{{optional for='$#meta_title'}}<title>{$#meta_title}</title>{{/optional}}
<meta name="keywords" content="{$#meta_keywords}" />
<meta name="description" content="{$#meta_description}" />
