{{wrap with="admin_page_layout.phtml"}}

  {{into slot="content_zone"}}

    <div id="header">
      <h1>Cron Jobs</h1>
      {{include file='_admin_include/pager.phtml' iterator='{$#items}'/}}
    </div>

    <div id="filter">
      {{form id="filter_form" name="filter_form" method="GET"}}
        <label for="job_name">Select cron:</label>
        {{select name="job_name" id="job_name" options="{$#job_names}"}}
          {{option prepend="true" value=""}}--All--{{/option}}
        {{/select}}

        <label for="only_failed">{{js_checkbox name='only_failed' id='only_failed' /}} Only failed?</label>

        {{input type="submit" name="submit" id="submit" value="Show" /}}
      {{/form}}
    </div>

    <div id="body">
      <dl id="items">
        {{list using="{$this->items}" as="$item"}}
          {{list:item}}
            <? $add_class = ($item['status'] == CronJobLogger::STATUS_ERROR || $item['status'] == CronJobLogger::STATUS_EXCEPTION || $item['status'] == CronJobLogger::STATUS_CONFLICT) ? 'warning' : 'success';?>
            <dt class='{$add_class}'>{$item.time|date:'d.m.Y - H:i:s'} | {$item.id} | {$item.path} | {$item.status}</dt>
            <dd>{$item.info|raw|nl2br}</dd>
          {{/list:item}}
        {{/list}}
      </dl>
    </div>
  {{/into}}

  {{into slot="css_zone"}}
    #items dt{background-color:#F5F5F5; margin:0px 0px 0px 0px; padding:10px;}
    #items dt.warning{color:red; }
    #items dt.success{color:green;}
    #items dd{padding:2px 0px 8px 0px;}
    #filter {margin:15px 0 25px 12px;}
      #filter .button_wrapper{margin:0 0 0 10px;}
  {{/into}}

{{/wrap}}