<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- Powered by LIMB | http://www.limb-project.com/ -->
<!-- Designed by BIT | http://www.bit-creative.com/ -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="description" content="<?php echo limb\lib\cms\src\model\lmbCmsSeo :: getMetaDescription(); ?>"/>
  <meta name="keywords" content="<?php echo limb\lib\cms\src\model\lmbCmsSeo :: getMetaKeywords(); ?>"/>
  <title><?php echo limb\lib\cms\src\model\lmbCmsSeo :: getMetaTitle(); ?></title>
</head>
<body>

  {{slot id='content_zone'/}}

</body>
</html>
