#!/usr/bin/php
<?php
/*
  Parameters:
  -d - Enable debug mode
  -v - Display output content
  -ld - Disable start and end job logging
*/

include(dirname(__FILE__) . '/../../lib/bit-cms/cron/cli/cron_runner.php');

?>
