<a href="<?php
    $uri = request()->getUri()->withQueryItem('sort',$field)->withQueryItem('direction','asc'); echo $uri->toString();
?>" title="Сортировать по возрастанию"><img src="/shared/cms/images/icons/arrow_down.png" alt="Сортировать по возрастанию"/></a>
<a href="<?php
    $uri = request()->getUri()->withQueryItem('sort',$field)->withQueryItem('direction','desc'); echo $uri->toString();
?>" title="Сортировать по убыванию"><img src="/shared/cms/images/icons/arrow_up.png" alt="Сортировать по убыванию"/></a>
