{{wrap with="_admin/popup.phtml" into="content_zone"}}
<?php
  $this->items = MetaInfo :: findByIds( $this->ids );
?>
<h1 class='delete'>Удаление записей</h1>

<div id="content_block">
{{form id='delete_form' class="list" action='' method='post'}}
  <table width='100%'>
  <tr>
    <th class="selector">{{include file='_admin/selector.phtml' /}}</th>
    <th>Заголовок</th>
  </tr>
  {{list using='$#items' parity='$parity'}}
  {{list:item}}
    <tr class='{$parity}'>
      <td><input type='checkbox' name='ids[]' value='{$item.id}' checked='true' /></td>
      <td><b>{$item.url}</b> {$item.title}</td>
    </tr>
  {{/list:item}}
  {{/list}}
  </table>

  {{include file='_admin/delete_common_elements.phtml' /}}
{{/form}}
</div>
{{/wrap}}
