{{wrap with="_admin/page.phtml" into="content_zone"}}
<div id="header_block">
  <h1>Мета-данные (SEO)</h1>

  <div class="header_actions">
    <a href='{{route_url params="controller:admin_seo,action:create"/}}' class='popup create'>Добавить элемент</a>
  </div>

  {{include file='_admin/notify_zone.phtml' /}}
</div>

<div id="content_block">
  <form name='list_form' method='post' class="list">
    <table>
      <tr>
        <th width='20%'>URL</th>
        <th width='20%'>Заголовок</th>
        <th width='60%'>Metadata</th>
        <th>Действия</th>
        </tr>
        {{list using='$#items' parity='$parity'}}
        {{list:item}}
        <tr class='{$parity}'>
          <td><a href="{$item.url}" style="font-weight: bold;">{$item.url}</a></td>
          <td>{$item.title}</td>
          <td>
            <dl class="cms_meta">
              <dt><b>Keywords</b></dt><dd>{$item.keywords}</dd>
              <dt><b>Description</b></dt><dd>{$item.description}</dd>
            </dl>
          </td>
          <td class='actions'>
            <a href='{{route_url params="action:edit,id:{$item.id}" /}}' class='popup' title="Редактировать"><img src='shared/cms/images/icon/action/edit.gif' width='16' height='17' alt='Редактировать'/></a>
            <a href='{{route_url params="action:delete?ids[]={$item.id}" /}}' class='popup' title="Удалить"><img src='shared/cms/images/icon/action/delete.gif' width='14' height='17' alt='Удалить'/></a>
          </td>
        </tr>
        {{/list:item}}
      </table>
    </form>
  {{/list}}
</div>
{{/wrap}}
